ResturantAkinator/ResturantAkinator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food-roots', include("foodRoots.urls"))
]

ResturantAkinator/foodRoots/urls.py
from django.urls import path, include

from . import views

app_name = "foodRoots"
urlpatterns = [
    path("", views.index, name="index"),
    path("/start", views.start, name="start"),
    path("/reset", views.reset, name="reset"),
]

ResturantAkinator/foodRoots/models.py
from django.db import models

# Create your models here.

ResturantAkinator/foodRoots/views.py
from django.shortcuts import render
from django import forms

from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

import csv
from os import path
from typing import List

QUESTIONS = {
    "chinese": ["Would you like to try Congee?", "What about dimsum?"
                , "Are you feeling noodles?", "Feeling a little spicy?"],
    "japanese": [
            "Would you like to try raw cuisine?",
            "Are you feeling some ramen?"
        ]
}

VALUES = {
    "chinese": ["congee", "dimsum"
                , "noodles", "spicy", "seafood"],
    "japanese": [
        "sushi", "ramen", "tempura"
        ]
}


class CultureForm(forms.Form):
    CHOICES = [("chinese", "Chinese"),
               ("japanese", "Japaense"),
               ]

    answer = forms.ChoiceField(
        widget=forms.RadioSelect(attrs={'class': 'custom'}),
        choices=CHOICES,
        label="")

class YesOrNoForm(forms.Form):
    CHOICES = [("yes", "Yes"),
               ("no", "No"),
               ]
    answer = forms.ChoiceField(
        widget=forms.RadioSelect(attrs={'class': 'custom'}),
        choices=CHOICES,
        label="")

def index(request):
    return render(request, "foodRoots/index.html")

def start(request):
    if request.method == "GET":
        reset(request)

        if len(request.session["answers"]) == 0:
            form = CultureForm()

        return render(request, "foodRoots/start.html", {
        "current_question_num": request.session["current_question_num"]+1,
        "current_question": request.session["current_question"],
        "form": form
        })

    elif request.method == "POST":
        if len(request.session["answers"]) == 0:

            post_form = CultureForm(request.POST)
            form = CultureForm()
        else:
            post_form = YesOrNoForm(request.POST)
            form = YesOrNoForm()

        if not post_form.is_valid():
            return render(request, "foodRoots/start.html", {
                "question_num": request.session["current_question_num"]+1,
                "question": request.session["current_question"],
                "form": form
            })

        answer = post_form.cleaned_data["answer"]
        request.session["answers"].append(answer)
        request.session.modified = True

        form = YesOrNoForm()

        if len(request.session["answers"]) == len(QUESTIONS[request.session["answers"][0]])+1 or request.session["answers"][-1] == "yes":
            if request.session["answers"][-1] == "no":
                sub_value = 1
            else:
                sub_value = 2

            print(len(request.session["answers"]))
            print(sub_value)

            resturants = _get_list_of_resturants(VALUES[request.session["answers"][0]][len(request.session["answers"])-sub_value])

            return render(request, "foodRoots/resturants.html", {
                "resturants": resturants
            })

        request.session["current_question_num"] = len(request.session["answers"])
        request.session["current_question"] = QUESTIONS[request.session["answers"][0]][request.session["current_question_num"]-1]

        return render(request, "foodRoots/start.html", {
        "current_question_num": request.session["current_question_num"]+1,
        "current_question": request.session["current_question"],
        "form": form
        })

def reset(request):
    request.session["answers"] = []
    request.session["current_question_num"] = 0
    request.session["current_question"] = "What is your cultural background?"
    return HttpResponseRedirect(reverse("foodRoots:start"))

def _get_list_of_resturants(attr: str) -> List[str]:
    with open(path.abspath("./foodRoots/food_db/food.csv")) as csv_file:
        csv_reader = csv.reader(csv_file, delimiter=",")
        print(attr)
        resturants = []
        for row in csv_reader:
            if attr in row:
                resturants.append((row[0], row[-1]))

        return resturants

ResturantAkinator/foodRoots/templates/foodRoots/index.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Culture Food Roots</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <h1>Discover the Food Roots of Your Culture!</h1>

        <script src="" async defer></script>
    </body>
</html>

ResturantAkinator/foodRoots/templates/foodRoots/resturants.html
{% load static %}

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Resturants</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'foodRoots/resturants.css' %}">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sofia">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <div id="main-content">
            <ul>
                {% for row in resturants %}
                    {% for element in row %}
                    <h2>{{ element }}</h2>
                    {% endfor %}
                {% endfor %}
            </ul>
        </div>
        <form action="{% url 'foodRoots:index' %}">
            <input type="submit" class="btn btn-secondary" class="text-dark" value="Home">
        </form>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <script src="" async defer></script>
    </body>
</html>

ResturantAkinator/foodRoots/templates/foodRoots/start.html
{% load static %}

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Culture Food Roots</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'foodRoots/start-styles.css' %}">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sofia">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <h2 id="question">{{ current_question_num }}. {{ current_question }}</h2>
        <form action="{% url 'foodRoots:start' %}" method="post" autocomplete="off">
            {% csrf_token %}
            {{ form }}
            <br>
            <input type="submit" class="btn btn-secondary" class="text-dark" value="Submit">
        </form>
        <br>
        <form action="{% url 'foodRoots:reset' %}">
            <input type="submit" class="btn btn-secondary" class="text-dark" value="Reset">
        </form>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
    </body>
</html>